crayola = [
    '#ED0A3F' /**Red */,
    '#FD0E35' /**Scarlet */,
    '#C62D42' /**Brick Red */,
    '#B94E48' /**Chestnut */,
    '#FE6F5E' /**Bittersweet */,
    '#FF7034' /**Burnt Orange */,
    '#FF681F' /**Red-Orange */,
    '#FF8833' /**Orange */,
    '#FFB97B' /**Macaroni and Cheese */,
    '#FFAE42' /**Yellow-Orange */,
    '#FCD667' /**Goldenrod */,
    '#FED85D' /**Dandelion */,
    '#FBE870' /**Yellow */,
    '#F1E788' /**Green-Yellow */,
    '#B5B35C' /**Olive Green */,
    '#ECEBBD' /**Spring Green */,
    '#C5E17A' /**Yellow-Green */,
    '#7BA05B' /**Asparagus */,
    '#9DE093' /**Granny Smith Apple */,
    '#01A638' /**Green */,
    '#5FA777' /**Forest Green */,
    '#93DFB8' /**Sea Green */,
    '#00CCCC' /**Robin's Egg Blue */,
    '#6CDAE7' /**Turquoise Blue */,
    '#76D7EA' /**Sky Blue */,
    '#0095B7' /**Blue-Green */,
    '#009DC4' /**Pacific Blue */,
    '#02A4D3' /**Cerulean */,
    '#93CCEA' /**Cornflower */,
    '#0066FF' /**Blue (III) */,
    '#A9B2C3' /**Cadet Blue */,
    '#C3CDE6' /**Periwinkle */,
    '#3C69E7' /**Bluetiful */,
    '#4F69C6' /**Indigo */,
    '#6456B7' /**Blue-Violet */,
    '#8359A3' /**Violet (II) */,
    '#C9A0DC' /**Wisteria */,
    '#D6AEDD' /**Purple Mountains' Majesty */,
    '#8E3179' /**Plum */,
    '#BB3385' /**Red-Violet */,
    '#F653A6' /**Magenta */,
    '#FF3399' /**Wild Strawberry */,
    '#FBAED2' /**Lavender (II) */,
    '#FFA6C9' /**Carnation Pink */,
    '#F7468A' /**Violet-Red */,
    '#FC80A5' /**Tickle Me Pink */,
    '#F091A9' /**Mauvelous */,
    '#FF91A4' /**Salmon */,
    '#CA3435' /**Mahogany */,
    '#FEBAAD' /**Melon */,
    '#E97451' /**Burnt Sienna */,
    '#AF593E' /**Brown */,
    '#9E5B40' /**Sepia */,
    '#DEA681' /**Tumbleweed */,
    '#D27D46' /**Raw Sienna */,
    '#FA9D5A' /**Tan */,
    '#FFCBA4' /**Peach */,
    '#FDD5B1' /**Apricot */,
    '#E6BE8A' /**Gold (II) */,
    '#C9C0BB' /**Silver */,
    '#000000' /**Black */,
    '#8B8680' /**Gray */,
    '#D9D6CF' /**Timberwolf */,
    '#FFFFFF' /**White */,
]